# Adapted from https://github.com/chriskempson/tomorrow-theme/blob/ccf6666d888198d341b26b3a99d0bc96500ad503/iTerm2/Tomorrow%20Night.itermcolors
# See licenses/chriskempson.txt for the upstream license.
[theme]
background = "#1d1f21"
foreground = "#c5c8c6"
cursor = "#c5c8c6"
selection = "#373b41"
selection_foreground = "#c5c8c6"
ansi_black = "#000000"
ansi_red = "#cc6666"
ansi_green = "#b5bd68"
ansi_yellow = "#f0c674"
ansi_blue = "#81a2be"
ansi_magenta = "#b294bb"
ansi_cyan = "#8abeb7"
ansi_white = "#ffffff"
ansi_bright_black = "#000000"
ansi_bright_red = "#cc6666"
ansi_bright_green = "#b5bd68"
ansi_bright_yellow = "#f0c674"
ansi_bright_blue = "#81a2be"
ansi_bright_magenta = "#b294bb"
ansi_bright_cyan = "#8abeb7"
ansi_bright_white = "#ffffff"
