[package]
name = "huterm-core"
description = "PTY, emulator, runtime, and mux ownership for Huterm"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version = "0.15.1"

[dependencies]
async-channel.workspace = true
huterm-ghostty.workspace = true
huterm-procinfo.workspace = true
huterm-protocol.workspace = true
memchr.workspace = true
portable-pty.workspace = true
thiserror.workspace = true
url = "=2.5.8"

[target.'cfg(unix)'.dependencies]
filedescriptor.workspace = true
nix.workspace = true

[lints]
workspace = true
