// @generated by huterm-ghostty-bindgen from Ghostty's C headers (header key annotations).
// Do not edit; run `mise run ghostty:bindings`.

//! Key markers and the Rust type each header annotation names.

use super::bindings as ffi;

/// Keys of `GhosttyTerminalData` from `terminal.h`.
pub(crate) mod terminal_data {
    use super::ffi;

    /// `GHOSTTY_TERMINAL_DATA_COLS`.
    #[derive(Debug)]
    pub(crate) enum Cols {}

    impl super::super::TerminalData for Cols {
        const KEY: ffi::GhosttyTerminalData = ffi::GHOSTTY_TERMINAL_DATA_COLS;
        type Out = u16;
    }

    /// `GHOSTTY_TERMINAL_DATA_ROWS`.
    #[derive(Debug)]
    pub(crate) enum Rows {}

    impl super::super::TerminalData for Rows {
        const KEY: ffi::GhosttyTerminalData = ffi::GHOSTTY_TERMINAL_DATA_ROWS;
        type Out = u16;
    }

    /// `GHOSTTY_TERMINAL_DATA_ACTIVE_SCREEN`.
    #[derive(Debug)]
    pub(crate) enum ActiveScreen {}

    impl super::super::TerminalData for ActiveScreen {
        const KEY: ffi::GhosttyTerminalData =
            ffi::GHOSTTY_TERMINAL_DATA_ACTIVE_SCREEN;
        type Out = ffi::GhosttyTerminalScreen;
    }

    /// `GHOSTTY_TERMINAL_DATA_SCROLLBAR`.
    #[derive(Debug)]
    pub(crate) enum Scrollbar {}

    impl super::super::TerminalData for Scrollbar {
        const KEY: ffi::GhosttyTerminalData =
            ffi::GHOSTTY_TERMINAL_DATA_SCROLLBAR;
        type Out = ffi::GhosttyTerminalScrollbar;
    }

    /// `GHOSTTY_TERMINAL_DATA_MOUSE_TRACKING`.
    #[derive(Debug)]
    pub(crate) enum MouseTracking {}

    impl super::super::TerminalData for MouseTracking {
        const KEY: ffi::GhosttyTerminalData =
            ffi::GHOSTTY_TERMINAL_DATA_MOUSE_TRACKING;
        type Out = bool;
    }

    /// `GHOSTTY_TERMINAL_DATA_TITLE`.
    #[derive(Debug)]
    pub(crate) enum Title {}

    impl super::super::TerminalData for Title {
        const KEY: ffi::GhosttyTerminalData = ffi::GHOSTTY_TERMINAL_DATA_TITLE;
        type Out = ffi::GhosttyString;
    }

    /// `GHOSTTY_TERMINAL_DATA_PWD`.
    #[derive(Debug)]
    pub(crate) enum Pwd {}

    impl super::super::TerminalData for Pwd {
        const KEY: ffi::GhosttyTerminalData = ffi::GHOSTTY_TERMINAL_DATA_PWD;
        type Out = ffi::GhosttyString;
    }

    /// `GHOSTTY_TERMINAL_DATA_TOTAL_ROWS`.
    #[derive(Debug)]
    pub(crate) enum TotalRows {}

    impl super::super::TerminalData for TotalRows {
        const KEY: ffi::GhosttyTerminalData =
            ffi::GHOSTTY_TERMINAL_DATA_TOTAL_ROWS;
        type Out = usize;
    }

    /// `GHOSTTY_TERMINAL_DATA_SCROLLBACK_ROWS`.
    #[derive(Debug)]
    pub(crate) enum ScrollbackRows {}

    impl super::super::TerminalData for ScrollbackRows {
        const KEY: ffi::GhosttyTerminalData =
            ffi::GHOSTTY_TERMINAL_DATA_SCROLLBACK_ROWS;
        type Out = usize;
    }

    /// `GHOSTTY_TERMINAL_DATA_COLOR_FOREGROUND`.
    #[derive(Debug)]
    pub(crate) enum ColorForeground {}

    impl super::super::TerminalData for ColorForeground {
        const KEY: ffi::GhosttyTerminalData =
            ffi::GHOSTTY_TERMINAL_DATA_COLOR_FOREGROUND;
        type Out = ffi::GhosttyColorRgb;
    }

    /// `GHOSTTY_TERMINAL_DATA_COLOR_BACKGROUND`.
    #[derive(Debug)]
    pub(crate) enum ColorBackground {}

    impl super::super::TerminalData for ColorBackground {
        const KEY: ffi::GhosttyTerminalData =
            ffi::GHOSTTY_TERMINAL_DATA_COLOR_BACKGROUND;
        type Out = ffi::GhosttyColorRgb;
    }

    /// `GHOSTTY_TERMINAL_DATA_COLOR_CURSOR`.
    #[derive(Debug)]
    pub(crate) enum ColorCursor {}

    impl super::super::TerminalData for ColorCursor {
        const KEY: ffi::GhosttyTerminalData =
            ffi::GHOSTTY_TERMINAL_DATA_COLOR_CURSOR;
        type Out = ffi::GhosttyColorRgb;
    }

    /// `GHOSTTY_TERMINAL_DATA_COLOR_PALETTE`.
    #[derive(Debug)]
    pub(crate) enum ColorPalette {}

    impl super::super::TerminalData for ColorPalette {
        const KEY: ffi::GhosttyTerminalData =
            ffi::GHOSTTY_TERMINAL_DATA_COLOR_PALETTE;
        type Out = [ffi::GhosttyColorRgb; 256];
    }

    /// `GHOSTTY_TERMINAL_DATA_COLOR_FOREGROUND_DEFAULT`.
    #[derive(Debug)]
    pub(crate) enum ColorForegroundDefault {}

    impl super::super::TerminalData for ColorForegroundDefault {
        const KEY: ffi::GhosttyTerminalData =
            ffi::GHOSTTY_TERMINAL_DATA_COLOR_FOREGROUND_DEFAULT;
        type Out = ffi::GhosttyColorRgb;
    }

    /// `GHOSTTY_TERMINAL_DATA_COLOR_BACKGROUND_DEFAULT`.
    #[derive(Debug)]
    pub(crate) enum ColorBackgroundDefault {}

    impl super::super::TerminalData for ColorBackgroundDefault {
        const KEY: ffi::GhosttyTerminalData =
            ffi::GHOSTTY_TERMINAL_DATA_COLOR_BACKGROUND_DEFAULT;
        type Out = ffi::GhosttyColorRgb;
    }

    /// `GHOSTTY_TERMINAL_DATA_COLOR_CURSOR_DEFAULT`.
    #[derive(Debug)]
    pub(crate) enum ColorCursorDefault {}

    impl super::super::TerminalData for ColorCursorDefault {
        const KEY: ffi::GhosttyTerminalData =
            ffi::GHOSTTY_TERMINAL_DATA_COLOR_CURSOR_DEFAULT;
        type Out = ffi::GhosttyColorRgb;
    }

    /// `GHOSTTY_TERMINAL_DATA_COLOR_PALETTE_DEFAULT`.
    #[derive(Debug)]
    pub(crate) enum ColorPaletteDefault {}

    impl super::super::TerminalData for ColorPaletteDefault {
        const KEY: ffi::GhosttyTerminalData =
            ffi::GHOSTTY_TERMINAL_DATA_COLOR_PALETTE_DEFAULT;
        type Out = [ffi::GhosttyColorRgb; 256];
    }

    /// `GHOSTTY_TERMINAL_DATA_KITTY_IMAGE_STORAGE_LIMIT`.
    #[derive(Debug)]
    pub(crate) enum KittyImageStorageLimit {}

    impl super::super::TerminalData for KittyImageStorageLimit {
        const KEY: ffi::GhosttyTerminalData =
            ffi::GHOSTTY_TERMINAL_DATA_KITTY_IMAGE_STORAGE_LIMIT;
        type Out = u64;
    }

    /// `GHOSTTY_TERMINAL_DATA_SCROLLBACK_MAX_BYTES`.
    #[derive(Debug)]
    pub(crate) enum ScrollbackMaxBytes {}

    impl super::super::TerminalData for ScrollbackMaxBytes {
        const KEY: ffi::GhosttyTerminalData =
            ffi::GHOSTTY_TERMINAL_DATA_SCROLLBACK_MAX_BYTES;
        type Out = usize;
    }

    /// `GHOSTTY_TERMINAL_DATA_MODE`.
    #[derive(Debug)]
    pub(crate) enum Mode {}

    impl super::super::TerminalData for Mode {
        const KEY: ffi::GhosttyTerminalData = ffi::GHOSTTY_TERMINAL_DATA_MODE;
        type Out = ffi::GhosttyTerminalModeConfig;
    }

    /// `GHOSTTY_TERMINAL_DATA_VT_GROUND`.
    #[derive(Debug)]
    pub(crate) enum VtGround {}

    impl super::super::TerminalData for VtGround {
        const KEY: ffi::GhosttyTerminalData =
            ffi::GHOSTTY_TERMINAL_DATA_VT_GROUND;
        type Out = bool;
    }
}

/// Keys of `GhosttyTerminalOption` from `terminal.h`.
pub(crate) mod terminal_option {
    use super::ffi;

    /// `GHOSTTY_TERMINAL_OPT_USERDATA`.
    #[derive(Debug)]
    pub(crate) enum Userdata {}

    impl super::super::TerminalPointer for Userdata {
        const KEY: ffi::GhosttyTerminalOption =
            ffi::GHOSTTY_TERMINAL_OPT_USERDATA;
    }

    /// `GHOSTTY_TERMINAL_OPT_WRITE_PTY`.
    #[derive(Debug)]
    pub(crate) enum WritePty {}

    impl super::super::TerminalCallback for WritePty {
        const KEY: ffi::GhosttyTerminalOption =
            ffi::GHOSTTY_TERMINAL_OPT_WRITE_PTY;
        type Callback = ffi::GhosttyTerminalWritePtyFn;
    }

    /// `GHOSTTY_TERMINAL_OPT_BELL`.
    #[derive(Debug)]
    pub(crate) enum Bell {}

    impl super::super::TerminalCallback for Bell {
        const KEY: ffi::GhosttyTerminalOption = ffi::GHOSTTY_TERMINAL_OPT_BELL;
        type Callback = ffi::GhosttyTerminalBellFn;
    }

    /// `GHOSTTY_TERMINAL_OPT_XTVERSION`.
    #[derive(Debug)]
    pub(crate) enum Xtversion {}

    impl super::super::TerminalCallback for Xtversion {
        const KEY: ffi::GhosttyTerminalOption =
            ffi::GHOSTTY_TERMINAL_OPT_XTVERSION;
        type Callback = ffi::GhosttyTerminalXtversionFn;
    }

    /// `GHOSTTY_TERMINAL_OPT_TITLE_CHANGED`.
    #[derive(Debug)]
    pub(crate) enum TitleChanged {}

    impl super::super::TerminalCallback for TitleChanged {
        const KEY: ffi::GhosttyTerminalOption =
            ffi::GHOSTTY_TERMINAL_OPT_TITLE_CHANGED;
        type Callback = ffi::GhosttyTerminalTitleChangedFn;
    }

    /// `GHOSTTY_TERMINAL_OPT_SIZE`.
    #[derive(Debug)]
    pub(crate) enum Size {}

    impl super::super::TerminalCallback for Size {
        const KEY: ffi::GhosttyTerminalOption = ffi::GHOSTTY_TERMINAL_OPT_SIZE;
        type Callback = ffi::GhosttyTerminalSizeFn;
    }

    /// `GHOSTTY_TERMINAL_OPT_COLOR_SCHEME`.
    #[derive(Debug)]
    pub(crate) enum ColorScheme {}

    impl super::super::TerminalCallback for ColorScheme {
        const KEY: ffi::GhosttyTerminalOption =
            ffi::GHOSTTY_TERMINAL_OPT_COLOR_SCHEME;
        type Callback = ffi::GhosttyTerminalColorSchemeFn;
    }

    /// `GHOSTTY_TERMINAL_OPT_DEVICE_ATTRIBUTES`.
    #[derive(Debug)]
    pub(crate) enum DeviceAttributes {}

    impl super::super::TerminalCallback for DeviceAttributes {
        const KEY: ffi::GhosttyTerminalOption =
            ffi::GHOSTTY_TERMINAL_OPT_DEVICE_ATTRIBUTES;
        type Callback = ffi::GhosttyTerminalDeviceAttributesFn;
    }

    /// `GHOSTTY_TERMINAL_OPT_COLOR_FOREGROUND`.
    #[derive(Debug)]
    pub(crate) enum ColorForeground {}

    impl super::super::TerminalOption for ColorForeground {
        const KEY: ffi::GhosttyTerminalOption =
            ffi::GHOSTTY_TERMINAL_OPT_COLOR_FOREGROUND;
        type Value = ffi::GhosttyColorRgb;
    }

    /// `GHOSTTY_TERMINAL_OPT_COLOR_BACKGROUND`.
    #[derive(Debug)]
    pub(crate) enum ColorBackground {}

    impl super::super::TerminalOption for ColorBackground {
        const KEY: ffi::GhosttyTerminalOption =
            ffi::GHOSTTY_TERMINAL_OPT_COLOR_BACKGROUND;
        type Value = ffi::GhosttyColorRgb;
    }

    /// `GHOSTTY_TERMINAL_OPT_COLOR_CURSOR`.
    #[derive(Debug)]
    pub(crate) enum ColorCursor {}

    impl super::super::TerminalOption for ColorCursor {
        const KEY: ffi::GhosttyTerminalOption =
            ffi::GHOSTTY_TERMINAL_OPT_COLOR_CURSOR;
        type Value = ffi::GhosttyColorRgb;
    }

    /// `GHOSTTY_TERMINAL_OPT_COLOR_PALETTE`.
    #[derive(Debug)]
    pub(crate) enum ColorPalette {}

    impl super::super::TerminalOption for ColorPalette {
        const KEY: ffi::GhosttyTerminalOption =
            ffi::GHOSTTY_TERMINAL_OPT_COLOR_PALETTE;
        type Value = [ffi::GhosttyColorRgb; 256];
    }

    /// `GHOSTTY_TERMINAL_OPT_KITTY_IMAGE_STORAGE_LIMIT`.
    #[derive(Debug)]
    pub(crate) enum KittyImageStorageLimit {}

    impl super::super::TerminalOption for KittyImageStorageLimit {
        const KEY: ffi::GhosttyTerminalOption =
            ffi::GHOSTTY_TERMINAL_OPT_KITTY_IMAGE_STORAGE_LIMIT;
        type Value = u64;
    }

    /// `GHOSTTY_TERMINAL_OPT_APC_MAX_BYTES`.
    #[derive(Debug)]
    pub(crate) enum ApcMaxBytes {}

    impl super::super::TerminalOption for ApcMaxBytes {
        const KEY: ffi::GhosttyTerminalOption =
            ffi::GHOSTTY_TERMINAL_OPT_APC_MAX_BYTES;
        type Value = usize;
    }

    /// `GHOSTTY_TERMINAL_OPT_GLYPH_PROTOCOL`.
    #[derive(Debug)]
    pub(crate) enum GlyphProtocol {}

    impl super::super::TerminalOption for GlyphProtocol {
        const KEY: ffi::GhosttyTerminalOption =
            ffi::GHOSTTY_TERMINAL_OPT_GLYPH_PROTOCOL;
        type Value = bool;
    }

    /// `GHOSTTY_TERMINAL_OPT_PWD_CHANGED`.
    #[derive(Debug)]
    pub(crate) enum PwdChanged {}

    impl super::super::TerminalCallback for PwdChanged {
        const KEY: ffi::GhosttyTerminalOption =
            ffi::GHOSTTY_TERMINAL_OPT_PWD_CHANGED;
        type Callback = ffi::GhosttyTerminalPwdChangedFn;
    }

    /// `GHOSTTY_TERMINAL_OPT_CLIPBOARD_WRITE`.
    #[derive(Debug)]
    pub(crate) enum ClipboardWrite {}

    impl super::super::TerminalCallback for ClipboardWrite {
        const KEY: ffi::GhosttyTerminalOption =
            ffi::GHOSTTY_TERMINAL_OPT_CLIPBOARD_WRITE;
        type Callback = ffi::GhosttyTerminalClipboardWriteFn;
    }

    /// `GHOSTTY_TERMINAL_OPT_SCROLLBACK_MAX_BYTES`.
    #[derive(Debug)]
    pub(crate) enum ScrollbackMaxBytes {}

    impl super::super::TerminalOption for ScrollbackMaxBytes {
        const KEY: ffi::GhosttyTerminalOption =
            ffi::GHOSTTY_TERMINAL_OPT_SCROLLBACK_MAX_BYTES;
        type Value = usize;
    }

    /// `GHOSTTY_TERMINAL_OPT_CLIPBOARD_WRITE_MAX_BYTES`.
    #[derive(Debug)]
    pub(crate) enum ClipboardWriteMaxBytes {}

    impl super::super::TerminalOption for ClipboardWriteMaxBytes {
        const KEY: ffi::GhosttyTerminalOption =
            ffi::GHOSTTY_TERMINAL_OPT_CLIPBOARD_WRITE_MAX_BYTES;
        type Value = usize;
    }
}

/// Keys of `GhosttyRenderStateData` from `render.h`.
pub(crate) mod render_state_data {
    use super::ffi;

    /// `GHOSTTY_RENDER_STATE_DATA_DIRTY`.
    #[derive(Debug)]
    pub(crate) enum Dirty {}

    impl super::super::RenderStateData for Dirty {
        const KEY: ffi::GhosttyRenderStateData =
            ffi::GHOSTTY_RENDER_STATE_DATA_DIRTY;
        type Out = ffi::GhosttyRenderStateDirty;
    }

    /// `GHOSTTY_RENDER_STATE_DATA_ROW_ITERATOR`.
    #[derive(Debug)]
    pub(crate) enum RowIterator {}

    impl super::super::RenderStateData for RowIterator {
        const KEY: ffi::GhosttyRenderStateData =
            ffi::GHOSTTY_RENDER_STATE_DATA_ROW_ITERATOR;
        type Out = ffi::GhosttyRenderStateRowIterator;
    }

    /// `GHOSTTY_RENDER_STATE_DATA_CURSOR`.
    #[derive(Debug)]
    pub(crate) enum Cursor {}

    impl super::super::RenderStateData for Cursor {
        const KEY: ffi::GhosttyRenderStateData =
            ffi::GHOSTTY_RENDER_STATE_DATA_CURSOR;
        type Out = ffi::GhosttyRenderStateCursor;
    }

    /// `GHOSTTY_RENDER_STATE_DATA_COLORS`.
    #[derive(Debug)]
    pub(crate) enum Colors {}

    impl super::super::RenderStateData for Colors {
        const KEY: ffi::GhosttyRenderStateData =
            ffi::GHOSTTY_RENDER_STATE_DATA_COLORS;
        type Out = ffi::GhosttyRenderStateColors;
    }
}

/// Keys of `GhosttyRenderStateRowData` from `render.h`.
pub(crate) mod render_row_data {
    use super::ffi;

    /// `GHOSTTY_RENDER_STATE_ROW_DATA_DIRTY`.
    #[derive(Debug)]
    pub(crate) enum Dirty {}

    impl super::super::RenderRowData for Dirty {
        const KEY: ffi::GhosttyRenderStateRowData =
            ffi::GHOSTTY_RENDER_STATE_ROW_DATA_DIRTY;
        type Out = bool;
    }

    /// `GHOSTTY_RENDER_STATE_ROW_DATA_RAW`.
    #[derive(Debug)]
    pub(crate) enum Raw {}

    impl super::super::RenderRowData for Raw {
        const KEY: ffi::GhosttyRenderStateRowData =
            ffi::GHOSTTY_RENDER_STATE_ROW_DATA_RAW;
        type Out = ffi::GhosttyRow;
    }

    /// `GHOSTTY_RENDER_STATE_ROW_DATA_CELLS`.
    #[derive(Debug)]
    pub(crate) enum Cells {}

    impl super::super::RenderRowData for Cells {
        const KEY: ffi::GhosttyRenderStateRowData =
            ffi::GHOSTTY_RENDER_STATE_ROW_DATA_CELLS;
        type Out = ffi::GhosttyRenderStateRowCells;
    }
}

/// Keys of `GhosttyRenderStateRowCellsData` from `render.h`.
pub(crate) mod render_cell_data {
    use super::ffi;

    /// `GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_RAW`.
    #[derive(Debug)]
    pub(crate) enum Raw {}

    impl super::super::RenderCellData for Raw {
        const KEY: ffi::GhosttyRenderStateRowCellsData =
            ffi::GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_RAW;
        type Out = ffi::GhosttyCell;
    }

    /// `GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_STYLE`.
    #[derive(Debug)]
    pub(crate) enum Style {}

    impl super::super::RenderCellData for Style {
        const KEY: ffi::GhosttyRenderStateRowCellsData =
            ffi::GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_STYLE;
        type Out = ffi::GhosttyStyle;
    }

    /// `GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_GRAPHEMES_UTF8`.
    #[derive(Debug)]
    pub(crate) enum GraphemesUtf8 {}

    impl super::super::RenderCellData for GraphemesUtf8 {
        const KEY: ffi::GhosttyRenderStateRowCellsData =
            ffi::GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_GRAPHEMES_UTF8;
        type Out = ffi::GhosttyBuffer;
    }
}

/// Keys of `GhosttyCellData` from `screen.h`.
pub(crate) mod cell_data {
    use super::ffi;

    /// `GHOSTTY_CELL_DATA_CODEPOINT`.
    #[derive(Debug)]
    pub(crate) enum Codepoint {}

    impl super::super::CellData for Codepoint {
        const KEY: ffi::GhosttyCellData = ffi::GHOSTTY_CELL_DATA_CODEPOINT;
        type Out = u32;
    }

    /// `GHOSTTY_CELL_DATA_CONTENT_TAG`.
    #[derive(Debug)]
    pub(crate) enum ContentTag {}

    impl super::super::CellData for ContentTag {
        const KEY: ffi::GhosttyCellData = ffi::GHOSTTY_CELL_DATA_CONTENT_TAG;
        type Out = ffi::GhosttyCellContentTag;
    }

    /// `GHOSTTY_CELL_DATA_WIDE`.
    #[derive(Debug)]
    pub(crate) enum Wide {}

    impl super::super::CellData for Wide {
        const KEY: ffi::GhosttyCellData = ffi::GHOSTTY_CELL_DATA_WIDE;
        type Out = ffi::GhosttyCellWide;
    }

    /// `GHOSTTY_CELL_DATA_HAS_TEXT`.
    #[derive(Debug)]
    pub(crate) enum HasText {}

    impl super::super::CellData for HasText {
        const KEY: ffi::GhosttyCellData = ffi::GHOSTTY_CELL_DATA_HAS_TEXT;
        type Out = bool;
    }

    /// `GHOSTTY_CELL_DATA_HAS_STYLING`.
    #[derive(Debug)]
    pub(crate) enum HasStyling {}

    impl super::super::CellData for HasStyling {
        const KEY: ffi::GhosttyCellData = ffi::GHOSTTY_CELL_DATA_HAS_STYLING;
        type Out = bool;
    }

    /// `GHOSTTY_CELL_DATA_HAS_HYPERLINK`.
    #[derive(Debug)]
    pub(crate) enum HasHyperlink {}

    impl super::super::CellData for HasHyperlink {
        const KEY: ffi::GhosttyCellData = ffi::GHOSTTY_CELL_DATA_HAS_HYPERLINK;
        type Out = bool;
    }

    /// `GHOSTTY_CELL_DATA_COLOR_PALETTE`.
    #[derive(Debug)]
    pub(crate) enum ColorPalette {}

    impl super::super::CellData for ColorPalette {
        const KEY: ffi::GhosttyCellData = ffi::GHOSTTY_CELL_DATA_COLOR_PALETTE;
        type Out = ffi::GhosttyColorPaletteIndex;
    }

    /// `GHOSTTY_CELL_DATA_COLOR_RGB`.
    #[derive(Debug)]
    pub(crate) enum ColorRgb {}

    impl super::super::CellData for ColorRgb {
        const KEY: ffi::GhosttyCellData = ffi::GHOSTTY_CELL_DATA_COLOR_RGB;
        type Out = ffi::GhosttyColorRgb;
    }
}

/// Keys of `GhosttyRowData` from `screen.h`.
pub(crate) mod row_data {
    use super::ffi;

    /// `GHOSTTY_ROW_DATA_WRAP`.
    #[derive(Debug)]
    pub(crate) enum Wrap {}

    impl super::super::RowData for Wrap {
        const KEY: ffi::GhosttyRowData = ffi::GHOSTTY_ROW_DATA_WRAP;
        type Out = bool;
    }

    /// `GHOSTTY_ROW_DATA_GRAPHEME`.
    #[derive(Debug)]
    pub(crate) enum Grapheme {}

    impl super::super::RowData for Grapheme {
        const KEY: ffi::GhosttyRowData = ffi::GHOSTTY_ROW_DATA_GRAPHEME;
        type Out = bool;
    }

    /// `GHOSTTY_ROW_DATA_STYLED`.
    #[derive(Debug)]
    pub(crate) enum Styled {}

    impl super::super::RowData for Styled {
        const KEY: ffi::GhosttyRowData = ffi::GHOSTTY_ROW_DATA_STYLED;
        type Out = bool;
    }
}

/// Keys of `GhosttyMouseEncoderOption` from `mouse/encoder.h`.
pub(crate) mod mouse_encoder_option {
    use super::ffi;

    /// `GHOSTTY_MOUSE_ENCODER_OPT_EVENT`.
    #[derive(Debug)]
    pub(crate) enum Event {}

    impl super::super::MouseEncoderOption for Event {
        const KEY: ffi::GhosttyMouseEncoderOption =
            ffi::GHOSTTY_MOUSE_ENCODER_OPT_EVENT;
        type Value = ffi::GhosttyMouseTrackingMode;
    }

    /// `GHOSTTY_MOUSE_ENCODER_OPT_SIZE`.
    #[derive(Debug)]
    pub(crate) enum Size {}

    impl super::super::MouseEncoderOption for Size {
        const KEY: ffi::GhosttyMouseEncoderOption =
            ffi::GHOSTTY_MOUSE_ENCODER_OPT_SIZE;
        type Value = ffi::GhosttyMouseEncoderSize;
    }

    /// `GHOSTTY_MOUSE_ENCODER_OPT_ANY_BUTTON_PRESSED`.
    #[derive(Debug)]
    pub(crate) enum AnyButtonPressed {}

    impl super::super::MouseEncoderOption for AnyButtonPressed {
        const KEY: ffi::GhosttyMouseEncoderOption =
            ffi::GHOSTTY_MOUSE_ENCODER_OPT_ANY_BUTTON_PRESSED;
        type Value = bool;
    }

    /// `GHOSTTY_MOUSE_ENCODER_OPT_TRACK_LAST_CELL`.
    #[derive(Debug)]
    pub(crate) enum TrackLastCell {}

    impl super::super::MouseEncoderOption for TrackLastCell {
        const KEY: ffi::GhosttyMouseEncoderOption =
            ffi::GHOSTTY_MOUSE_ENCODER_OPT_TRACK_LAST_CELL;
        type Value = bool;
    }
}

/// Keys of `GhosttyBuildInfo` from `build_info.h`.
pub(crate) mod build_info {
    use super::ffi;

    /// `GHOSTTY_BUILD_INFO_OPTIMIZE`.
    #[derive(Debug)]
    pub(crate) enum Optimize {}

    impl super::super::BuildInfo for Optimize {
        const KEY: ffi::GhosttyBuildInfo = ffi::GHOSTTY_BUILD_INFO_OPTIMIZE;
        type Out = ffi::GhosttyOptimizeMode;
    }
}

impl super::SizedStruct for ffi::GhosttyStyle {
    fn size_mut(&mut self) -> &mut usize {
        &mut self.size
    }
}

impl super::SizedStruct for ffi::GhosttyGridRef {
    fn size_mut(&mut self) -> &mut usize {
        &mut self.size
    }
}

impl super::SizedStruct for ffi::GhosttySelection {
    fn size_mut(&mut self) -> &mut usize {
        &mut self.size
    }
}

impl super::SizedStruct for ffi::GhosttyTerminalSelectionFormatOptions {
    fn size_mut(&mut self) -> &mut usize {
        &mut self.size
    }
}

impl super::SizedStruct for ffi::GhosttyClipboardWriteReply {
    fn size_mut(&mut self) -> &mut usize {
        &mut self.size
    }
}

impl super::SizedStruct for ffi::GhosttyClipboardWrite {
    fn size_mut(&mut self) -> &mut usize {
        &mut self.size
    }
}

impl super::SizedStruct for ffi::GhosttyRenderStateCursor {
    fn size_mut(&mut self) -> &mut usize {
        &mut self.size
    }
}

impl super::SizedStruct for ffi::GhosttyRenderStateColors {
    fn size_mut(&mut self) -> &mut usize {
        &mut self.size
    }
}

impl super::SizedStruct for ffi::GhosttyMouseEncoderSize {
    fn size_mut(&mut self) -> &mut usize {
        &mut self.size
    }
}
