// @generated by huterm-ghostty-bindgen from Ghostty's C headers (bindgen output).
// Do not edit; run `mise run ghostty:bindings`.

//! Rust layouts of every FFI type, compared with the linked library's
//! `ghostty_type_json()` manifest by the ABI test.

use core::mem::{align_of, offset_of, size_of};

use super::bindings as ffi;

pub(crate) struct Struct {
    pub(crate) name: &'static str,
    pub(crate) size: usize,
    pub(crate) align: usize,
    pub(crate) fields: &'static [(&'static str, usize)],
}

pub(crate) struct Sized {
    pub(crate) name: &'static str,
    pub(crate) size: usize,
    pub(crate) align: usize,
}

pub(crate) struct Enum {
    pub(crate) name: &'static str,
    pub(crate) size: usize,
    pub(crate) align: usize,
    pub(crate) values: &'static [(&'static str, i64)],
}

pub(crate) const STRUCTS: &[Struct] = &[
    Struct {
        name: "GhosttyString",
        size: size_of::<ffi::GhosttyString>(),
        align: align_of::<ffi::GhosttyString>(),
        fields: &[
            ("ptr", offset_of!(ffi::GhosttyString, ptr)),
            ("len", offset_of!(ffi::GhosttyString, len)),
        ],
    },
    Struct {
        name: "GhosttyBuffer",
        size: size_of::<ffi::GhosttyBuffer>(),
        align: align_of::<ffi::GhosttyBuffer>(),
        fields: &[
            ("ptr", offset_of!(ffi::GhosttyBuffer, ptr)),
            ("cap", offset_of!(ffi::GhosttyBuffer, cap)),
            ("len", offset_of!(ffi::GhosttyBuffer, len)),
        ],
    },
    Struct {
        name: "GhosttyAllocatorVtable",
        size: size_of::<ffi::GhosttyAllocatorVtable>(),
        align: align_of::<ffi::GhosttyAllocatorVtable>(),
        fields: &[
            ("alloc", offset_of!(ffi::GhosttyAllocatorVtable, alloc)),
            ("resize", offset_of!(ffi::GhosttyAllocatorVtable, resize)),
            ("remap", offset_of!(ffi::GhosttyAllocatorVtable, remap)),
            ("free", offset_of!(ffi::GhosttyAllocatorVtable, free)),
        ],
    },
    Struct {
        name: "GhosttyAllocator",
        size: size_of::<ffi::GhosttyAllocator>(),
        align: align_of::<ffi::GhosttyAllocator>(),
        fields: &[
            ("ctx", offset_of!(ffi::GhosttyAllocator, ctx)),
            ("vtable", offset_of!(ffi::GhosttyAllocator, vtable)),
        ],
    },
    Struct {
        name: "GhosttyColorRgb",
        size: size_of::<ffi::GhosttyColorRgb>(),
        align: align_of::<ffi::GhosttyColorRgb>(),
        fields: &[
            ("r", offset_of!(ffi::GhosttyColorRgb, r)),
            ("g", offset_of!(ffi::GhosttyColorRgb, g)),
            ("b", offset_of!(ffi::GhosttyColorRgb, b)),
        ],
    },
    Struct {
        name: "GhosttyDeviceAttributesPrimary",
        size: size_of::<ffi::GhosttyDeviceAttributesPrimary>(),
        align: align_of::<ffi::GhosttyDeviceAttributesPrimary>(),
        fields: &[
            (
                "conformance_level",
                offset_of!(
                    ffi::GhosttyDeviceAttributesPrimary,
                    conformance_level
                ),
            ),
            (
                "features",
                offset_of!(ffi::GhosttyDeviceAttributesPrimary, features),
            ),
            (
                "num_features",
                offset_of!(ffi::GhosttyDeviceAttributesPrimary, num_features),
            ),
        ],
    },
    Struct {
        name: "GhosttyDeviceAttributesSecondary",
        size: size_of::<ffi::GhosttyDeviceAttributesSecondary>(),
        align: align_of::<ffi::GhosttyDeviceAttributesSecondary>(),
        fields: &[
            (
                "device_type",
                offset_of!(ffi::GhosttyDeviceAttributesSecondary, device_type),
            ),
            (
                "firmware_version",
                offset_of!(
                    ffi::GhosttyDeviceAttributesSecondary,
                    firmware_version
                ),
            ),
            (
                "rom_cartridge",
                offset_of!(
                    ffi::GhosttyDeviceAttributesSecondary,
                    rom_cartridge
                ),
            ),
        ],
    },
    Struct {
        name: "GhosttyDeviceAttributesTertiary",
        size: size_of::<ffi::GhosttyDeviceAttributesTertiary>(),
        align: align_of::<ffi::GhosttyDeviceAttributesTertiary>(),
        fields: &[(
            "unit_id",
            offset_of!(ffi::GhosttyDeviceAttributesTertiary, unit_id),
        )],
    },
    Struct {
        name: "GhosttyDeviceAttributes",
        size: size_of::<ffi::GhosttyDeviceAttributes>(),
        align: align_of::<ffi::GhosttyDeviceAttributes>(),
        fields: &[
            ("primary", offset_of!(ffi::GhosttyDeviceAttributes, primary)),
            (
                "secondary",
                offset_of!(ffi::GhosttyDeviceAttributes, secondary),
            ),
            (
                "tertiary",
                offset_of!(ffi::GhosttyDeviceAttributes, tertiary),
            ),
        ],
    },
    Struct {
        name: "GhosttyStyleColor",
        size: size_of::<ffi::GhosttyStyleColor>(),
        align: align_of::<ffi::GhosttyStyleColor>(),
        fields: &[
            ("tag", offset_of!(ffi::GhosttyStyleColor, tag)),
            ("value", offset_of!(ffi::GhosttyStyleColor, value)),
        ],
    },
    Struct {
        name: "GhosttyStyle",
        size: size_of::<ffi::GhosttyStyle>(),
        align: align_of::<ffi::GhosttyStyle>(),
        fields: &[
            ("size", offset_of!(ffi::GhosttyStyle, size)),
            ("fg_color", offset_of!(ffi::GhosttyStyle, fg_color)),
            ("bg_color", offset_of!(ffi::GhosttyStyle, bg_color)),
            (
                "underline_color",
                offset_of!(ffi::GhosttyStyle, underline_color),
            ),
            ("bold", offset_of!(ffi::GhosttyStyle, bold)),
            ("italic", offset_of!(ffi::GhosttyStyle, italic)),
            ("faint", offset_of!(ffi::GhosttyStyle, faint)),
            ("blink", offset_of!(ffi::GhosttyStyle, blink)),
            ("inverse", offset_of!(ffi::GhosttyStyle, inverse)),
            ("invisible", offset_of!(ffi::GhosttyStyle, invisible)),
            (
                "strikethrough",
                offset_of!(ffi::GhosttyStyle, strikethrough),
            ),
            ("overline", offset_of!(ffi::GhosttyStyle, overline)),
            ("underline", offset_of!(ffi::GhosttyStyle, underline)),
        ],
    },
    Struct {
        name: "GhosttyGridRef",
        size: size_of::<ffi::GhosttyGridRef>(),
        align: align_of::<ffi::GhosttyGridRef>(),
        fields: &[
            ("size", offset_of!(ffi::GhosttyGridRef, size)),
            ("node", offset_of!(ffi::GhosttyGridRef, node)),
            ("x", offset_of!(ffi::GhosttyGridRef, x)),
            ("y", offset_of!(ffi::GhosttyGridRef, y)),
        ],
    },
    Struct {
        name: "GhosttyPointCoordinate",
        size: size_of::<ffi::GhosttyPointCoordinate>(),
        align: align_of::<ffi::GhosttyPointCoordinate>(),
        fields: &[
            ("x", offset_of!(ffi::GhosttyPointCoordinate, x)),
            ("y", offset_of!(ffi::GhosttyPointCoordinate, y)),
        ],
    },
    Struct {
        name: "GhosttyPoint",
        size: size_of::<ffi::GhosttyPoint>(),
        align: align_of::<ffi::GhosttyPoint>(),
        fields: &[
            ("tag", offset_of!(ffi::GhosttyPoint, tag)),
            ("value", offset_of!(ffi::GhosttyPoint, value)),
        ],
    },
    Struct {
        name: "GhosttySelection",
        size: size_of::<ffi::GhosttySelection>(),
        align: align_of::<ffi::GhosttySelection>(),
        fields: &[
            ("size", offset_of!(ffi::GhosttySelection, size)),
            ("start", offset_of!(ffi::GhosttySelection, start)),
            ("end", offset_of!(ffi::GhosttySelection, end)),
            ("rectangle", offset_of!(ffi::GhosttySelection, rectangle)),
        ],
    },
    Struct {
        name: "GhosttyTerminalSelectionFormatOptions",
        size: size_of::<ffi::GhosttyTerminalSelectionFormatOptions>(),
        align: align_of::<ffi::GhosttyTerminalSelectionFormatOptions>(),
        fields: &[
            (
                "size",
                offset_of!(ffi::GhosttyTerminalSelectionFormatOptions, size),
            ),
            (
                "emit",
                offset_of!(ffi::GhosttyTerminalSelectionFormatOptions, emit),
            ),
            (
                "unwrap",
                offset_of!(ffi::GhosttyTerminalSelectionFormatOptions, unwrap),
            ),
            (
                "trim",
                offset_of!(ffi::GhosttyTerminalSelectionFormatOptions, trim),
            ),
            (
                "selection",
                offset_of!(
                    ffi::GhosttyTerminalSelectionFormatOptions,
                    selection
                ),
            ),
        ],
    },
    Struct {
        name: "GhosttySizeReportSize",
        size: size_of::<ffi::GhosttySizeReportSize>(),
        align: align_of::<ffi::GhosttySizeReportSize>(),
        fields: &[
            ("rows", offset_of!(ffi::GhosttySizeReportSize, rows)),
            ("columns", offset_of!(ffi::GhosttySizeReportSize, columns)),
            (
                "cell_width",
                offset_of!(ffi::GhosttySizeReportSize, cell_width),
            ),
            (
                "cell_height",
                offset_of!(ffi::GhosttySizeReportSize, cell_height),
            ),
        ],
    },
    Struct {
        name: "GhosttyTerminalScrollViewport",
        size: size_of::<ffi::GhosttyTerminalScrollViewport>(),
        align: align_of::<ffi::GhosttyTerminalScrollViewport>(),
        fields: &[
            ("tag", offset_of!(ffi::GhosttyTerminalScrollViewport, tag)),
            (
                "value",
                offset_of!(ffi::GhosttyTerminalScrollViewport, value),
            ),
        ],
    },
    Struct {
        name: "GhosttyTerminalScrollbar",
        size: size_of::<ffi::GhosttyTerminalScrollbar>(),
        align: align_of::<ffi::GhosttyTerminalScrollbar>(),
        fields: &[
            ("total", offset_of!(ffi::GhosttyTerminalScrollbar, total)),
            ("offset", offset_of!(ffi::GhosttyTerminalScrollbar, offset)),
            ("len", offset_of!(ffi::GhosttyTerminalScrollbar, len)),
        ],
    },
    Struct {
        name: "GhosttyClipboardContent",
        size: size_of::<ffi::GhosttyClipboardContent>(),
        align: align_of::<ffi::GhosttyClipboardContent>(),
        fields: &[
            ("mime", offset_of!(ffi::GhosttyClipboardContent, mime)),
            ("data", offset_of!(ffi::GhosttyClipboardContent, data)),
        ],
    },
    Struct {
        name: "GhosttyClipboardWriteReply",
        size: size_of::<ffi::GhosttyClipboardWriteReply>(),
        align: align_of::<ffi::GhosttyClipboardWriteReply>(),
        fields: &[
            ("size", offset_of!(ffi::GhosttyClipboardWriteReply, size)),
            (
                "result",
                offset_of!(ffi::GhosttyClipboardWriteReply, result),
            ),
            (
                "remember",
                offset_of!(ffi::GhosttyClipboardWriteReply, remember),
            ),
        ],
    },
    Struct {
        name: "GhosttyClipboardWrite",
        size: size_of::<ffi::GhosttyClipboardWrite>(),
        align: align_of::<ffi::GhosttyClipboardWrite>(),
        fields: &[
            ("size", offset_of!(ffi::GhosttyClipboardWrite, size)),
            ("location", offset_of!(ffi::GhosttyClipboardWrite, location)),
            ("contents", offset_of!(ffi::GhosttyClipboardWrite, contents)),
            (
                "contents_len",
                offset_of!(ffi::GhosttyClipboardWrite, contents_len),
            ),
            ("name", offset_of!(ffi::GhosttyClipboardWrite, name)),
            ("granted", offset_of!(ffi::GhosttyClipboardWrite, granted)),
            (
                "can_remember",
                offset_of!(ffi::GhosttyClipboardWrite, can_remember),
            ),
            ("ctx", offset_of!(ffi::GhosttyClipboardWrite, ctx)),
            ("reply", offset_of!(ffi::GhosttyClipboardWrite, reply)),
        ],
    },
    Struct {
        name: "GhosttyTerminalModeConfig",
        size: size_of::<ffi::GhosttyTerminalModeConfig>(),
        align: align_of::<ffi::GhosttyTerminalModeConfig>(),
        fields: &[
            ("mode", offset_of!(ffi::GhosttyTerminalModeConfig, mode)),
            ("value", offset_of!(ffi::GhosttyTerminalModeConfig, value)),
        ],
    },
    Struct {
        name: "GhosttyRenderStateCursor",
        size: size_of::<ffi::GhosttyRenderStateCursor>(),
        align: align_of::<ffi::GhosttyRenderStateCursor>(),
        fields: &[
            ("size", offset_of!(ffi::GhosttyRenderStateCursor, size)),
            (
                "viewport_has_value",
                offset_of!(ffi::GhosttyRenderStateCursor, viewport_has_value),
            ),
            (
                "viewport_x",
                offset_of!(ffi::GhosttyRenderStateCursor, viewport_x),
            ),
            (
                "viewport_y",
                offset_of!(ffi::GhosttyRenderStateCursor, viewport_y),
            ),
            (
                "wide_tail",
                offset_of!(ffi::GhosttyRenderStateCursor, wide_tail),
            ),
            (
                "visible",
                offset_of!(ffi::GhosttyRenderStateCursor, visible),
            ),
            (
                "blinking",
                offset_of!(ffi::GhosttyRenderStateCursor, blinking),
            ),
            (
                "password_input",
                offset_of!(ffi::GhosttyRenderStateCursor, password_input),
            ),
            (
                "visual_style",
                offset_of!(ffi::GhosttyRenderStateCursor, visual_style),
            ),
        ],
    },
    Struct {
        name: "GhosttyRenderStateColors",
        size: size_of::<ffi::GhosttyRenderStateColors>(),
        align: align_of::<ffi::GhosttyRenderStateColors>(),
        fields: &[
            ("size", offset_of!(ffi::GhosttyRenderStateColors, size)),
            (
                "background",
                offset_of!(ffi::GhosttyRenderStateColors, background),
            ),
            (
                "foreground",
                offset_of!(ffi::GhosttyRenderStateColors, foreground),
            ),
            ("cursor", offset_of!(ffi::GhosttyRenderStateColors, cursor)),
            (
                "cursor_has_value",
                offset_of!(ffi::GhosttyRenderStateColors, cursor_has_value),
            ),
            (
                "palette",
                offset_of!(ffi::GhosttyRenderStateColors, palette),
            ),
        ],
    },
    Struct {
        name: "GhosttyMousePosition",
        size: size_of::<ffi::GhosttyMousePosition>(),
        align: align_of::<ffi::GhosttyMousePosition>(),
        fields: &[
            ("x", offset_of!(ffi::GhosttyMousePosition, x)),
            ("y", offset_of!(ffi::GhosttyMousePosition, y)),
        ],
    },
    Struct {
        name: "GhosttyMouseEncoderSize",
        size: size_of::<ffi::GhosttyMouseEncoderSize>(),
        align: align_of::<ffi::GhosttyMouseEncoderSize>(),
        fields: &[
            ("size", offset_of!(ffi::GhosttyMouseEncoderSize, size)),
            (
                "screen_width",
                offset_of!(ffi::GhosttyMouseEncoderSize, screen_width),
            ),
            (
                "screen_height",
                offset_of!(ffi::GhosttyMouseEncoderSize, screen_height),
            ),
            (
                "cell_width",
                offset_of!(ffi::GhosttyMouseEncoderSize, cell_width),
            ),
            (
                "cell_height",
                offset_of!(ffi::GhosttyMouseEncoderSize, cell_height),
            ),
            (
                "padding_top",
                offset_of!(ffi::GhosttyMouseEncoderSize, padding_top),
            ),
            (
                "padding_bottom",
                offset_of!(ffi::GhosttyMouseEncoderSize, padding_bottom),
            ),
            (
                "padding_right",
                offset_of!(ffi::GhosttyMouseEncoderSize, padding_right),
            ),
            (
                "padding_left",
                offset_of!(ffi::GhosttyMouseEncoderSize, padding_left),
            ),
        ],
    },
];

pub(crate) const ENUMS: &[Enum] = &[
    Enum {
        name: "GhosttyResult",
        size: size_of::<ffi::GhosttyResult>(),
        align: align_of::<ffi::GhosttyResult>(),
        values: &[
            ("GHOSTTY_SUCCESS", ffi::GHOSTTY_SUCCESS as i64),
            ("GHOSTTY_OUT_OF_MEMORY", ffi::GHOSTTY_OUT_OF_MEMORY as i64),
            ("GHOSTTY_INVALID_VALUE", ffi::GHOSTTY_INVALID_VALUE as i64),
            ("GHOSTTY_OUT_OF_SPACE", ffi::GHOSTTY_OUT_OF_SPACE as i64),
            ("GHOSTTY_NO_VALUE", ffi::GHOSTTY_NO_VALUE as i64),
            ("GHOSTTY_IO_ERROR", ffi::GHOSTTY_IO_ERROR as i64),
            ("GHOSTTY_LIMIT_EXCEEDED", ffi::GHOSTTY_LIMIT_EXCEEDED as i64),
            ("GHOSTTY_REJECTED", ffi::GHOSTTY_REJECTED as i64),
            (
                "GHOSTTY_RESULT_MAX_VALUE",
                ffi::GHOSTTY_RESULT_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyFormatterFormat",
        size: size_of::<ffi::GhosttyFormatterFormat>(),
        align: align_of::<ffi::GhosttyFormatterFormat>(),
        values: &[
            (
                "GHOSTTY_FORMATTER_FORMAT_PLAIN",
                ffi::GHOSTTY_FORMATTER_FORMAT_PLAIN as i64,
            ),
            (
                "GHOSTTY_FORMATTER_FORMAT_VT",
                ffi::GHOSTTY_FORMATTER_FORMAT_VT as i64,
            ),
            (
                "GHOSTTY_FORMATTER_FORMAT_HTML",
                ffi::GHOSTTY_FORMATTER_FORMAT_HTML as i64,
            ),
            (
                "GHOSTTY_FORMATTER_FORMAT_MAX_VALUE",
                ffi::GHOSTTY_FORMATTER_FORMAT_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyOptimizeMode",
        size: size_of::<ffi::GhosttyOptimizeMode>(),
        align: align_of::<ffi::GhosttyOptimizeMode>(),
        values: &[
            ("GHOSTTY_OPTIMIZE_DEBUG", ffi::GHOSTTY_OPTIMIZE_DEBUG as i64),
            (
                "GHOSTTY_OPTIMIZE_RELEASE_SAFE",
                ffi::GHOSTTY_OPTIMIZE_RELEASE_SAFE as i64,
            ),
            (
                "GHOSTTY_OPTIMIZE_RELEASE_SMALL",
                ffi::GHOSTTY_OPTIMIZE_RELEASE_SMALL as i64,
            ),
            (
                "GHOSTTY_OPTIMIZE_RELEASE_FAST",
                ffi::GHOSTTY_OPTIMIZE_RELEASE_FAST as i64,
            ),
            (
                "GHOSTTY_OPTIMIZE_MODE_MAX_VALUE",
                ffi::GHOSTTY_OPTIMIZE_MODE_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyBuildInfo",
        size: size_of::<ffi::GhosttyBuildInfo>(),
        align: align_of::<ffi::GhosttyBuildInfo>(),
        values: &[
            (
                "GHOSTTY_BUILD_INFO_INVALID",
                ffi::GHOSTTY_BUILD_INFO_INVALID as i64,
            ),
            (
                "GHOSTTY_BUILD_INFO_SIMD",
                ffi::GHOSTTY_BUILD_INFO_SIMD as i64,
            ),
            (
                "GHOSTTY_BUILD_INFO_KITTY_GRAPHICS",
                ffi::GHOSTTY_BUILD_INFO_KITTY_GRAPHICS as i64,
            ),
            (
                "GHOSTTY_BUILD_INFO_TMUX_CONTROL_MODE",
                ffi::GHOSTTY_BUILD_INFO_TMUX_CONTROL_MODE as i64,
            ),
            (
                "GHOSTTY_BUILD_INFO_OPTIMIZE",
                ffi::GHOSTTY_BUILD_INFO_OPTIMIZE as i64,
            ),
            (
                "GHOSTTY_BUILD_INFO_VERSION_STRING",
                ffi::GHOSTTY_BUILD_INFO_VERSION_STRING as i64,
            ),
            (
                "GHOSTTY_BUILD_INFO_VERSION_MAJOR",
                ffi::GHOSTTY_BUILD_INFO_VERSION_MAJOR as i64,
            ),
            (
                "GHOSTTY_BUILD_INFO_VERSION_MINOR",
                ffi::GHOSTTY_BUILD_INFO_VERSION_MINOR as i64,
            ),
            (
                "GHOSTTY_BUILD_INFO_VERSION_PATCH",
                ffi::GHOSTTY_BUILD_INFO_VERSION_PATCH as i64,
            ),
            (
                "GHOSTTY_BUILD_INFO_VERSION_PRE",
                ffi::GHOSTTY_BUILD_INFO_VERSION_PRE as i64,
            ),
            (
                "GHOSTTY_BUILD_INFO_VERSION_BUILD",
                ffi::GHOSTTY_BUILD_INFO_VERSION_BUILD as i64,
            ),
            (
                "GHOSTTY_BUILD_INFO_MAX_VALUE",
                ffi::GHOSTTY_BUILD_INFO_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyColorScheme",
        size: size_of::<ffi::GhosttyColorScheme>(),
        align: align_of::<ffi::GhosttyColorScheme>(),
        values: &[
            (
                "GHOSTTY_COLOR_SCHEME_LIGHT",
                ffi::GHOSTTY_COLOR_SCHEME_LIGHT as i64,
            ),
            (
                "GHOSTTY_COLOR_SCHEME_DARK",
                ffi::GHOSTTY_COLOR_SCHEME_DARK as i64,
            ),
            (
                "GHOSTTY_COLOR_SCHEME_MAX_VALUE",
                ffi::GHOSTTY_COLOR_SCHEME_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyCellContentTag",
        size: size_of::<ffi::GhosttyCellContentTag>(),
        align: align_of::<ffi::GhosttyCellContentTag>(),
        values: &[
            (
                "GHOSTTY_CELL_CONTENT_CODEPOINT",
                ffi::GHOSTTY_CELL_CONTENT_CODEPOINT as i64,
            ),
            (
                "GHOSTTY_CELL_CONTENT_CODEPOINT_GRAPHEME",
                ffi::GHOSTTY_CELL_CONTENT_CODEPOINT_GRAPHEME as i64,
            ),
            (
                "GHOSTTY_CELL_CONTENT_BG_COLOR_PALETTE",
                ffi::GHOSTTY_CELL_CONTENT_BG_COLOR_PALETTE as i64,
            ),
            (
                "GHOSTTY_CELL_CONTENT_BG_COLOR_RGB",
                ffi::GHOSTTY_CELL_CONTENT_BG_COLOR_RGB as i64,
            ),
            (
                "GHOSTTY_CELL_CONTENT_TAG_MAX_VALUE",
                ffi::GHOSTTY_CELL_CONTENT_TAG_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyCellWide",
        size: size_of::<ffi::GhosttyCellWide>(),
        align: align_of::<ffi::GhosttyCellWide>(),
        values: &[
            (
                "GHOSTTY_CELL_WIDE_NARROW",
                ffi::GHOSTTY_CELL_WIDE_NARROW as i64,
            ),
            ("GHOSTTY_CELL_WIDE_WIDE", ffi::GHOSTTY_CELL_WIDE_WIDE as i64),
            (
                "GHOSTTY_CELL_WIDE_SPACER_TAIL",
                ffi::GHOSTTY_CELL_WIDE_SPACER_TAIL as i64,
            ),
            (
                "GHOSTTY_CELL_WIDE_SPACER_HEAD",
                ffi::GHOSTTY_CELL_WIDE_SPACER_HEAD as i64,
            ),
            (
                "GHOSTTY_CELL_WIDE_MAX_VALUE",
                ffi::GHOSTTY_CELL_WIDE_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyCellData",
        size: size_of::<ffi::GhosttyCellData>(),
        align: align_of::<ffi::GhosttyCellData>(),
        values: &[
            (
                "GHOSTTY_CELL_DATA_INVALID",
                ffi::GHOSTTY_CELL_DATA_INVALID as i64,
            ),
            (
                "GHOSTTY_CELL_DATA_CODEPOINT",
                ffi::GHOSTTY_CELL_DATA_CODEPOINT as i64,
            ),
            (
                "GHOSTTY_CELL_DATA_CONTENT_TAG",
                ffi::GHOSTTY_CELL_DATA_CONTENT_TAG as i64,
            ),
            ("GHOSTTY_CELL_DATA_WIDE", ffi::GHOSTTY_CELL_DATA_WIDE as i64),
            (
                "GHOSTTY_CELL_DATA_HAS_TEXT",
                ffi::GHOSTTY_CELL_DATA_HAS_TEXT as i64,
            ),
            (
                "GHOSTTY_CELL_DATA_HAS_STYLING",
                ffi::GHOSTTY_CELL_DATA_HAS_STYLING as i64,
            ),
            (
                "GHOSTTY_CELL_DATA_STYLE_ID",
                ffi::GHOSTTY_CELL_DATA_STYLE_ID as i64,
            ),
            (
                "GHOSTTY_CELL_DATA_HAS_HYPERLINK",
                ffi::GHOSTTY_CELL_DATA_HAS_HYPERLINK as i64,
            ),
            (
                "GHOSTTY_CELL_DATA_PROTECTED",
                ffi::GHOSTTY_CELL_DATA_PROTECTED as i64,
            ),
            (
                "GHOSTTY_CELL_DATA_SEMANTIC_CONTENT",
                ffi::GHOSTTY_CELL_DATA_SEMANTIC_CONTENT as i64,
            ),
            (
                "GHOSTTY_CELL_DATA_COLOR_PALETTE",
                ffi::GHOSTTY_CELL_DATA_COLOR_PALETTE as i64,
            ),
            (
                "GHOSTTY_CELL_DATA_COLOR_RGB",
                ffi::GHOSTTY_CELL_DATA_COLOR_RGB as i64,
            ),
            (
                "GHOSTTY_CELL_DATA_MAX_VALUE",
                ffi::GHOSTTY_CELL_DATA_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyRowData",
        size: size_of::<ffi::GhosttyRowData>(),
        align: align_of::<ffi::GhosttyRowData>(),
        values: &[
            (
                "GHOSTTY_ROW_DATA_INVALID",
                ffi::GHOSTTY_ROW_DATA_INVALID as i64,
            ),
            ("GHOSTTY_ROW_DATA_WRAP", ffi::GHOSTTY_ROW_DATA_WRAP as i64),
            (
                "GHOSTTY_ROW_DATA_WRAP_CONTINUATION",
                ffi::GHOSTTY_ROW_DATA_WRAP_CONTINUATION as i64,
            ),
            (
                "GHOSTTY_ROW_DATA_GRAPHEME",
                ffi::GHOSTTY_ROW_DATA_GRAPHEME as i64,
            ),
            (
                "GHOSTTY_ROW_DATA_STYLED",
                ffi::GHOSTTY_ROW_DATA_STYLED as i64,
            ),
            (
                "GHOSTTY_ROW_DATA_HYPERLINK",
                ffi::GHOSTTY_ROW_DATA_HYPERLINK as i64,
            ),
            (
                "GHOSTTY_ROW_DATA_SEMANTIC_PROMPT",
                ffi::GHOSTTY_ROW_DATA_SEMANTIC_PROMPT as i64,
            ),
            (
                "GHOSTTY_ROW_DATA_KITTY_VIRTUAL_PLACEHOLDER",
                ffi::GHOSTTY_ROW_DATA_KITTY_VIRTUAL_PLACEHOLDER as i64,
            ),
            ("GHOSTTY_ROW_DATA_DIRTY", ffi::GHOSTTY_ROW_DATA_DIRTY as i64),
            (
                "GHOSTTY_ROW_DATA_MAX_VALUE",
                ffi::GHOSTTY_ROW_DATA_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyStyleColorTag",
        size: size_of::<ffi::GhosttyStyleColorTag>(),
        align: align_of::<ffi::GhosttyStyleColorTag>(),
        values: &[
            (
                "GHOSTTY_STYLE_COLOR_NONE",
                ffi::GHOSTTY_STYLE_COLOR_NONE as i64,
            ),
            (
                "GHOSTTY_STYLE_COLOR_PALETTE",
                ffi::GHOSTTY_STYLE_COLOR_PALETTE as i64,
            ),
            (
                "GHOSTTY_STYLE_COLOR_RGB",
                ffi::GHOSTTY_STYLE_COLOR_RGB as i64,
            ),
            (
                "GHOSTTY_STYLE_COLOR_TAG_MAX_VALUE",
                ffi::GHOSTTY_STYLE_COLOR_TAG_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyPointTag",
        size: size_of::<ffi::GhosttyPointTag>(),
        align: align_of::<ffi::GhosttyPointTag>(),
        values: &[
            (
                "GHOSTTY_POINT_TAG_ACTIVE",
                ffi::GHOSTTY_POINT_TAG_ACTIVE as i64,
            ),
            (
                "GHOSTTY_POINT_TAG_VIEWPORT",
                ffi::GHOSTTY_POINT_TAG_VIEWPORT as i64,
            ),
            (
                "GHOSTTY_POINT_TAG_SCREEN",
                ffi::GHOSTTY_POINT_TAG_SCREEN as i64,
            ),
            (
                "GHOSTTY_POINT_TAG_HISTORY",
                ffi::GHOSTTY_POINT_TAG_HISTORY as i64,
            ),
            (
                "GHOSTTY_POINT_TAG_MAX_VALUE",
                ffi::GHOSTTY_POINT_TAG_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyTerminalScrollViewportTag",
        size: size_of::<ffi::GhosttyTerminalScrollViewportTag>(),
        align: align_of::<ffi::GhosttyTerminalScrollViewportTag>(),
        values: &[
            (
                "GHOSTTY_SCROLL_VIEWPORT_TOP",
                ffi::GHOSTTY_SCROLL_VIEWPORT_TOP as i64,
            ),
            (
                "GHOSTTY_SCROLL_VIEWPORT_BOTTOM",
                ffi::GHOSTTY_SCROLL_VIEWPORT_BOTTOM as i64,
            ),
            (
                "GHOSTTY_SCROLL_VIEWPORT_DELTA",
                ffi::GHOSTTY_SCROLL_VIEWPORT_DELTA as i64,
            ),
            (
                "GHOSTTY_SCROLL_VIEWPORT_ROW",
                ffi::GHOSTTY_SCROLL_VIEWPORT_ROW as i64,
            ),
            (
                "GHOSTTY_SCROLL_VIEWPORT_MAX_VALUE",
                ffi::GHOSTTY_SCROLL_VIEWPORT_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyTerminalScreen",
        size: size_of::<ffi::GhosttyTerminalScreen>(),
        align: align_of::<ffi::GhosttyTerminalScreen>(),
        values: &[
            (
                "GHOSTTY_TERMINAL_SCREEN_PRIMARY",
                ffi::GHOSTTY_TERMINAL_SCREEN_PRIMARY as i64,
            ),
            (
                "GHOSTTY_TERMINAL_SCREEN_ALTERNATE",
                ffi::GHOSTTY_TERMINAL_SCREEN_ALTERNATE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_SCREEN_MAX_VALUE",
                ffi::GHOSTTY_TERMINAL_SCREEN_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyClipboardLocation",
        size: size_of::<ffi::GhosttyClipboardLocation>(),
        align: align_of::<ffi::GhosttyClipboardLocation>(),
        values: &[
            (
                "GHOSTTY_CLIPBOARD_LOCATION_STANDARD",
                ffi::GHOSTTY_CLIPBOARD_LOCATION_STANDARD as i64,
            ),
            (
                "GHOSTTY_CLIPBOARD_LOCATION_SELECTION",
                ffi::GHOSTTY_CLIPBOARD_LOCATION_SELECTION as i64,
            ),
            (
                "GHOSTTY_CLIPBOARD_LOCATION_PRIMARY",
                ffi::GHOSTTY_CLIPBOARD_LOCATION_PRIMARY as i64,
            ),
            (
                "GHOSTTY_CLIPBOARD_LOCATION_MAX_VALUE",
                ffi::GHOSTTY_CLIPBOARD_LOCATION_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyClipboardWriteResult",
        size: size_of::<ffi::GhosttyClipboardWriteResult>(),
        align: align_of::<ffi::GhosttyClipboardWriteResult>(),
        values: &[
            (
                "GHOSTTY_CLIPBOARD_WRITE_RESULT_SUCCESS",
                ffi::GHOSTTY_CLIPBOARD_WRITE_RESULT_SUCCESS as i64,
            ),
            (
                "GHOSTTY_CLIPBOARD_WRITE_RESULT_DENIED",
                ffi::GHOSTTY_CLIPBOARD_WRITE_RESULT_DENIED as i64,
            ),
            (
                "GHOSTTY_CLIPBOARD_WRITE_RESULT_UNSUPPORTED",
                ffi::GHOSTTY_CLIPBOARD_WRITE_RESULT_UNSUPPORTED as i64,
            ),
            (
                "GHOSTTY_CLIPBOARD_WRITE_RESULT_BUSY",
                ffi::GHOSTTY_CLIPBOARD_WRITE_RESULT_BUSY as i64,
            ),
            (
                "GHOSTTY_CLIPBOARD_WRITE_RESULT_INVALID_DATA",
                ffi::GHOSTTY_CLIPBOARD_WRITE_RESULT_INVALID_DATA as i64,
            ),
            (
                "GHOSTTY_CLIPBOARD_WRITE_RESULT_IO_ERROR",
                ffi::GHOSTTY_CLIPBOARD_WRITE_RESULT_IO_ERROR as i64,
            ),
            (
                "GHOSTTY_CLIPBOARD_WRITE_RESULT_MAX_VALUE",
                ffi::GHOSTTY_CLIPBOARD_WRITE_RESULT_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyTerminalOption",
        size: size_of::<ffi::GhosttyTerminalOption>(),
        align: align_of::<ffi::GhosttyTerminalOption>(),
        values: &[
            (
                "GHOSTTY_TERMINAL_OPT_USERDATA",
                ffi::GHOSTTY_TERMINAL_OPT_USERDATA as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_WRITE_PTY",
                ffi::GHOSTTY_TERMINAL_OPT_WRITE_PTY as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_BELL",
                ffi::GHOSTTY_TERMINAL_OPT_BELL as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_ENQUIRY",
                ffi::GHOSTTY_TERMINAL_OPT_ENQUIRY as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_XTVERSION",
                ffi::GHOSTTY_TERMINAL_OPT_XTVERSION as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_TITLE_CHANGED",
                ffi::GHOSTTY_TERMINAL_OPT_TITLE_CHANGED as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_SIZE",
                ffi::GHOSTTY_TERMINAL_OPT_SIZE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_COLOR_SCHEME",
                ffi::GHOSTTY_TERMINAL_OPT_COLOR_SCHEME as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_DEVICE_ATTRIBUTES",
                ffi::GHOSTTY_TERMINAL_OPT_DEVICE_ATTRIBUTES as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_TITLE",
                ffi::GHOSTTY_TERMINAL_OPT_TITLE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_PWD",
                ffi::GHOSTTY_TERMINAL_OPT_PWD as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_COLOR_FOREGROUND",
                ffi::GHOSTTY_TERMINAL_OPT_COLOR_FOREGROUND as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_COLOR_BACKGROUND",
                ffi::GHOSTTY_TERMINAL_OPT_COLOR_BACKGROUND as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_COLOR_CURSOR",
                ffi::GHOSTTY_TERMINAL_OPT_COLOR_CURSOR as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_COLOR_PALETTE",
                ffi::GHOSTTY_TERMINAL_OPT_COLOR_PALETTE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_KITTY_IMAGE_STORAGE_LIMIT",
                ffi::GHOSTTY_TERMINAL_OPT_KITTY_IMAGE_STORAGE_LIMIT as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_KITTY_IMAGE_MEDIUM_FILE",
                ffi::GHOSTTY_TERMINAL_OPT_KITTY_IMAGE_MEDIUM_FILE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_KITTY_IMAGE_MEDIUM_TEMP_FILE",
                ffi::GHOSTTY_TERMINAL_OPT_KITTY_IMAGE_MEDIUM_TEMP_FILE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_KITTY_IMAGE_MEDIUM_SHARED_MEM",
                ffi::GHOSTTY_TERMINAL_OPT_KITTY_IMAGE_MEDIUM_SHARED_MEM as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_APC_MAX_BYTES",
                ffi::GHOSTTY_TERMINAL_OPT_APC_MAX_BYTES as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_APC_MAX_BYTES_KITTY",
                ffi::GHOSTTY_TERMINAL_OPT_APC_MAX_BYTES_KITTY as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_SELECTION",
                ffi::GHOSTTY_TERMINAL_OPT_SELECTION as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_DEFAULT_CURSOR_STYLE",
                ffi::GHOSTTY_TERMINAL_OPT_DEFAULT_CURSOR_STYLE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_DEFAULT_CURSOR_BLINK",
                ffi::GHOSTTY_TERMINAL_OPT_DEFAULT_CURSOR_BLINK as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_GLYPH_PROTOCOL",
                ffi::GHOSTTY_TERMINAL_OPT_GLYPH_PROTOCOL as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_PWD_CHANGED",
                ffi::GHOSTTY_TERMINAL_OPT_PWD_CHANGED as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_CLIPBOARD_WRITE",
                ffi::GHOSTTY_TERMINAL_OPT_CLIPBOARD_WRITE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_SCROLLBACK_MAX_BYTES",
                ffi::GHOSTTY_TERMINAL_OPT_SCROLLBACK_MAX_BYTES as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_SCROLLBACK_MAX_LINES",
                ffi::GHOSTTY_TERMINAL_OPT_SCROLLBACK_MAX_LINES as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_DESKTOP_NOTIFICATION",
                ffi::GHOSTTY_TERMINAL_OPT_DESKTOP_NOTIFICATION as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_PROGRESS_REPORT",
                ffi::GHOSTTY_TERMINAL_OPT_PROGRESS_REPORT as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_CONTINUATION_MAX_BYTES",
                ffi::GHOSTTY_TERMINAL_OPT_CONTINUATION_MAX_BYTES as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_TITLE_REPORT",
                ffi::GHOSTTY_TERMINAL_OPT_TITLE_REPORT as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_MODE_DEFAULT",
                ffi::GHOSTTY_TERMINAL_OPT_MODE_DEFAULT as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_MODE",
                ffi::GHOSTTY_TERMINAL_OPT_MODE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_UNKNOWN_SEQUENCE",
                ffi::GHOSTTY_TERMINAL_OPT_UNKNOWN_SEQUENCE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_UNKNOWN_MAX_BYTES",
                ffi::GHOSTTY_TERMINAL_OPT_UNKNOWN_MAX_BYTES as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_TERMINFO_NAME",
                ffi::GHOSTTY_TERMINAL_OPT_TERMINFO_NAME as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_CLIPBOARD_READ",
                ffi::GHOSTTY_TERMINAL_OPT_CLIPBOARD_READ as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_CLIPBOARD_WRITE_MAX_BYTES",
                ffi::GHOSTTY_TERMINAL_OPT_CLIPBOARD_WRITE_MAX_BYTES as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_RESIZE_PULL_SCROLLBACK",
                ffi::GHOSTTY_TERMINAL_OPT_RESIZE_PULL_SCROLLBACK as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_RENDER_HOLD",
                ffi::GHOSTTY_TERMINAL_OPT_RENDER_HOLD as i64,
            ),
            (
                "GHOSTTY_TERMINAL_OPT_MAX_VALUE",
                ffi::GHOSTTY_TERMINAL_OPT_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyTerminalData",
        size: size_of::<ffi::GhosttyTerminalData>(),
        align: align_of::<ffi::GhosttyTerminalData>(),
        values: &[
            (
                "GHOSTTY_TERMINAL_DATA_INVALID",
                ffi::GHOSTTY_TERMINAL_DATA_INVALID as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_COLS",
                ffi::GHOSTTY_TERMINAL_DATA_COLS as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_ROWS",
                ffi::GHOSTTY_TERMINAL_DATA_ROWS as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_CURSOR_X",
                ffi::GHOSTTY_TERMINAL_DATA_CURSOR_X as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_CURSOR_Y",
                ffi::GHOSTTY_TERMINAL_DATA_CURSOR_Y as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_CURSOR_PENDING_WRAP",
                ffi::GHOSTTY_TERMINAL_DATA_CURSOR_PENDING_WRAP as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_ACTIVE_SCREEN",
                ffi::GHOSTTY_TERMINAL_DATA_ACTIVE_SCREEN as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_CURSOR_VISIBLE",
                ffi::GHOSTTY_TERMINAL_DATA_CURSOR_VISIBLE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_KITTY_KEYBOARD_FLAGS",
                ffi::GHOSTTY_TERMINAL_DATA_KITTY_KEYBOARD_FLAGS as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_SCROLLBAR",
                ffi::GHOSTTY_TERMINAL_DATA_SCROLLBAR as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_CURSOR_STYLE",
                ffi::GHOSTTY_TERMINAL_DATA_CURSOR_STYLE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_MOUSE_TRACKING",
                ffi::GHOSTTY_TERMINAL_DATA_MOUSE_TRACKING as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_TITLE",
                ffi::GHOSTTY_TERMINAL_DATA_TITLE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_PWD",
                ffi::GHOSTTY_TERMINAL_DATA_PWD as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_TOTAL_ROWS",
                ffi::GHOSTTY_TERMINAL_DATA_TOTAL_ROWS as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_SCROLLBACK_ROWS",
                ffi::GHOSTTY_TERMINAL_DATA_SCROLLBACK_ROWS as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_WIDTH_PX",
                ffi::GHOSTTY_TERMINAL_DATA_WIDTH_PX as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_HEIGHT_PX",
                ffi::GHOSTTY_TERMINAL_DATA_HEIGHT_PX as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_COLOR_FOREGROUND",
                ffi::GHOSTTY_TERMINAL_DATA_COLOR_FOREGROUND as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_COLOR_BACKGROUND",
                ffi::GHOSTTY_TERMINAL_DATA_COLOR_BACKGROUND as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_COLOR_CURSOR",
                ffi::GHOSTTY_TERMINAL_DATA_COLOR_CURSOR as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_COLOR_PALETTE",
                ffi::GHOSTTY_TERMINAL_DATA_COLOR_PALETTE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_COLOR_FOREGROUND_DEFAULT",
                ffi::GHOSTTY_TERMINAL_DATA_COLOR_FOREGROUND_DEFAULT as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_COLOR_BACKGROUND_DEFAULT",
                ffi::GHOSTTY_TERMINAL_DATA_COLOR_BACKGROUND_DEFAULT as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_COLOR_CURSOR_DEFAULT",
                ffi::GHOSTTY_TERMINAL_DATA_COLOR_CURSOR_DEFAULT as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_COLOR_PALETTE_DEFAULT",
                ffi::GHOSTTY_TERMINAL_DATA_COLOR_PALETTE_DEFAULT as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_KITTY_IMAGE_STORAGE_LIMIT",
                ffi::GHOSTTY_TERMINAL_DATA_KITTY_IMAGE_STORAGE_LIMIT as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_KITTY_IMAGE_MEDIUM_FILE",
                ffi::GHOSTTY_TERMINAL_DATA_KITTY_IMAGE_MEDIUM_FILE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_KITTY_IMAGE_MEDIUM_TEMP_FILE",
                ffi::GHOSTTY_TERMINAL_DATA_KITTY_IMAGE_MEDIUM_TEMP_FILE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_KITTY_IMAGE_MEDIUM_SHARED_MEM",
                ffi::GHOSTTY_TERMINAL_DATA_KITTY_IMAGE_MEDIUM_SHARED_MEM as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_KITTY_GRAPHICS",
                ffi::GHOSTTY_TERMINAL_DATA_KITTY_GRAPHICS as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_SELECTION",
                ffi::GHOSTTY_TERMINAL_DATA_SELECTION as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_VIEWPORT_ACTIVE",
                ffi::GHOSTTY_TERMINAL_DATA_VIEWPORT_ACTIVE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_VT_PROCESSING_ERROR",
                ffi::GHOSTTY_TERMINAL_DATA_VT_PROCESSING_ERROR as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_SCROLLBACK_MAX_BYTES",
                ffi::GHOSTTY_TERMINAL_DATA_SCROLLBACK_MAX_BYTES as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_SCROLLBACK_MAX_LINES",
                ffi::GHOSTTY_TERMINAL_DATA_SCROLLBACK_MAX_LINES as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_CONTINUATION_MAX_BYTES",
                ffi::GHOSTTY_TERMINAL_DATA_CONTINUATION_MAX_BYTES as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_MODE",
                ffi::GHOSTTY_TERMINAL_DATA_MODE as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_VT_GROUND",
                ffi::GHOSTTY_TERMINAL_DATA_VT_GROUND as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_CURSOR_AT_PROMPT",
                ffi::GHOSTTY_TERMINAL_DATA_CURSOR_AT_PROMPT as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_CLIPBOARD_WRITE_MAX_BYTES",
                ffi::GHOSTTY_TERMINAL_DATA_CLIPBOARD_WRITE_MAX_BYTES as i64,
            ),
            (
                "GHOSTTY_TERMINAL_DATA_MAX_VALUE",
                ffi::GHOSTTY_TERMINAL_DATA_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyRenderStateDirty",
        size: size_of::<ffi::GhosttyRenderStateDirty>(),
        align: align_of::<ffi::GhosttyRenderStateDirty>(),
        values: &[
            (
                "GHOSTTY_RENDER_STATE_DIRTY_FALSE",
                ffi::GHOSTTY_RENDER_STATE_DIRTY_FALSE as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DIRTY_PARTIAL",
                ffi::GHOSTTY_RENDER_STATE_DIRTY_PARTIAL as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DIRTY_FULL",
                ffi::GHOSTTY_RENDER_STATE_DIRTY_FULL as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DIRTY_MAX_VALUE",
                ffi::GHOSTTY_RENDER_STATE_DIRTY_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyRenderStateCursorVisualStyle",
        size: size_of::<ffi::GhosttyRenderStateCursorVisualStyle>(),
        align: align_of::<ffi::GhosttyRenderStateCursorVisualStyle>(),
        values: &[
            (
                "GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_BAR",
                ffi::GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_BAR as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_BLOCK",
                ffi::GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_BLOCK as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_UNDERLINE",
                ffi::GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_UNDERLINE as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_BLOCK_HOLLOW",
                ffi::GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_BLOCK_HOLLOW
                    as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_MAX_VALUE",
                ffi::GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyRenderStateData",
        size: size_of::<ffi::GhosttyRenderStateData>(),
        align: align_of::<ffi::GhosttyRenderStateData>(),
        values: &[
            (
                "GHOSTTY_RENDER_STATE_DATA_INVALID",
                ffi::GHOSTTY_RENDER_STATE_DATA_INVALID as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_COLS",
                ffi::GHOSTTY_RENDER_STATE_DATA_COLS as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_ROWS",
                ffi::GHOSTTY_RENDER_STATE_DATA_ROWS as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_DIRTY",
                ffi::GHOSTTY_RENDER_STATE_DATA_DIRTY as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_ROW_ITERATOR",
                ffi::GHOSTTY_RENDER_STATE_DATA_ROW_ITERATOR as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_COLOR_BACKGROUND",
                ffi::GHOSTTY_RENDER_STATE_DATA_COLOR_BACKGROUND as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_COLOR_FOREGROUND",
                ffi::GHOSTTY_RENDER_STATE_DATA_COLOR_FOREGROUND as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_COLOR_CURSOR",
                ffi::GHOSTTY_RENDER_STATE_DATA_COLOR_CURSOR as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_COLOR_CURSOR_HAS_VALUE",
                ffi::GHOSTTY_RENDER_STATE_DATA_COLOR_CURSOR_HAS_VALUE as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_COLOR_PALETTE",
                ffi::GHOSTTY_RENDER_STATE_DATA_COLOR_PALETTE as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_CURSOR_VISUAL_STYLE",
                ffi::GHOSTTY_RENDER_STATE_DATA_CURSOR_VISUAL_STYLE as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_CURSOR_VISIBLE",
                ffi::GHOSTTY_RENDER_STATE_DATA_CURSOR_VISIBLE as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_CURSOR_BLINKING",
                ffi::GHOSTTY_RENDER_STATE_DATA_CURSOR_BLINKING as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_CURSOR_PASSWORD_INPUT",
                ffi::GHOSTTY_RENDER_STATE_DATA_CURSOR_PASSWORD_INPUT as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_CURSOR_VIEWPORT_HAS_VALUE",
                ffi::GHOSTTY_RENDER_STATE_DATA_CURSOR_VIEWPORT_HAS_VALUE as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_CURSOR_VIEWPORT_X",
                ffi::GHOSTTY_RENDER_STATE_DATA_CURSOR_VIEWPORT_X as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_CURSOR_VIEWPORT_Y",
                ffi::GHOSTTY_RENDER_STATE_DATA_CURSOR_VIEWPORT_Y as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_CURSOR_VIEWPORT_WIDE_TAIL",
                ffi::GHOSTTY_RENDER_STATE_DATA_CURSOR_VIEWPORT_WIDE_TAIL as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_CURSOR",
                ffi::GHOSTTY_RENDER_STATE_DATA_CURSOR as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_COLORS",
                ffi::GHOSTTY_RENDER_STATE_DATA_COLORS as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_DATA_MAX_VALUE",
                ffi::GHOSTTY_RENDER_STATE_DATA_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyRenderStateRowData",
        size: size_of::<ffi::GhosttyRenderStateRowData>(),
        align: align_of::<ffi::GhosttyRenderStateRowData>(),
        values: &[
            (
                "GHOSTTY_RENDER_STATE_ROW_DATA_INVALID",
                ffi::GHOSTTY_RENDER_STATE_ROW_DATA_INVALID as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_ROW_DATA_DIRTY",
                ffi::GHOSTTY_RENDER_STATE_ROW_DATA_DIRTY as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_ROW_DATA_RAW",
                ffi::GHOSTTY_RENDER_STATE_ROW_DATA_RAW as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_ROW_DATA_CELLS",
                ffi::GHOSTTY_RENDER_STATE_ROW_DATA_CELLS as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_ROW_DATA_SELECTION",
                ffi::GHOSTTY_RENDER_STATE_ROW_DATA_SELECTION as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_ROW_DATA_CELLS_RAW",
                ffi::GHOSTTY_RENDER_STATE_ROW_DATA_CELLS_RAW as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_ROW_DATA_MAX_VALUE",
                ffi::GHOSTTY_RENDER_STATE_ROW_DATA_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyRenderStateRowCellsData",
        size: size_of::<ffi::GhosttyRenderStateRowCellsData>(),
        align: align_of::<ffi::GhosttyRenderStateRowCellsData>(),
        values: &[
            (
                "GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_INVALID",
                ffi::GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_INVALID as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_RAW",
                ffi::GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_RAW as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_STYLE",
                ffi::GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_STYLE as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_GRAPHEMES_LEN",
                ffi::GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_GRAPHEMES_LEN as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_GRAPHEMES_BUF",
                ffi::GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_GRAPHEMES_BUF as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_BG_COLOR",
                ffi::GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_BG_COLOR as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_FG_COLOR",
                ffi::GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_FG_COLOR as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_SELECTED",
                ffi::GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_SELECTED as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_HAS_STYLING",
                ffi::GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_HAS_STYLING as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_GRAPHEMES_UTF8",
                ffi::GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_GRAPHEMES_UTF8 as i64,
            ),
            (
                "GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_MAX_VALUE",
                ffi::GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttySgrUnderline",
        size: size_of::<ffi::GhosttySgrUnderline>(),
        align: align_of::<ffi::GhosttySgrUnderline>(),
        values: &[
            (
                "GHOSTTY_SGR_UNDERLINE_NONE",
                ffi::GHOSTTY_SGR_UNDERLINE_NONE as i64,
            ),
            (
                "GHOSTTY_SGR_UNDERLINE_SINGLE",
                ffi::GHOSTTY_SGR_UNDERLINE_SINGLE as i64,
            ),
            (
                "GHOSTTY_SGR_UNDERLINE_DOUBLE",
                ffi::GHOSTTY_SGR_UNDERLINE_DOUBLE as i64,
            ),
            (
                "GHOSTTY_SGR_UNDERLINE_CURLY",
                ffi::GHOSTTY_SGR_UNDERLINE_CURLY as i64,
            ),
            (
                "GHOSTTY_SGR_UNDERLINE_DOTTED",
                ffi::GHOSTTY_SGR_UNDERLINE_DOTTED as i64,
            ),
            (
                "GHOSTTY_SGR_UNDERLINE_DASHED",
                ffi::GHOSTTY_SGR_UNDERLINE_DASHED as i64,
            ),
            (
                "GHOSTTY_SGR_UNDERLINE_MAX_VALUE",
                ffi::GHOSTTY_SGR_UNDERLINE_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyMouseAction",
        size: size_of::<ffi::GhosttyMouseAction>(),
        align: align_of::<ffi::GhosttyMouseAction>(),
        values: &[
            (
                "GHOSTTY_MOUSE_ACTION_PRESS",
                ffi::GHOSTTY_MOUSE_ACTION_PRESS as i64,
            ),
            (
                "GHOSTTY_MOUSE_ACTION_RELEASE",
                ffi::GHOSTTY_MOUSE_ACTION_RELEASE as i64,
            ),
            (
                "GHOSTTY_MOUSE_ACTION_MOTION",
                ffi::GHOSTTY_MOUSE_ACTION_MOTION as i64,
            ),
            (
                "GHOSTTY_MOUSE_ACTION_MAX_VALUE",
                ffi::GHOSTTY_MOUSE_ACTION_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyMouseButton",
        size: size_of::<ffi::GhosttyMouseButton>(),
        align: align_of::<ffi::GhosttyMouseButton>(),
        values: &[
            (
                "GHOSTTY_MOUSE_BUTTON_UNKNOWN",
                ffi::GHOSTTY_MOUSE_BUTTON_UNKNOWN as i64,
            ),
            (
                "GHOSTTY_MOUSE_BUTTON_LEFT",
                ffi::GHOSTTY_MOUSE_BUTTON_LEFT as i64,
            ),
            (
                "GHOSTTY_MOUSE_BUTTON_RIGHT",
                ffi::GHOSTTY_MOUSE_BUTTON_RIGHT as i64,
            ),
            (
                "GHOSTTY_MOUSE_BUTTON_MIDDLE",
                ffi::GHOSTTY_MOUSE_BUTTON_MIDDLE as i64,
            ),
            (
                "GHOSTTY_MOUSE_BUTTON_FOUR",
                ffi::GHOSTTY_MOUSE_BUTTON_FOUR as i64,
            ),
            (
                "GHOSTTY_MOUSE_BUTTON_FIVE",
                ffi::GHOSTTY_MOUSE_BUTTON_FIVE as i64,
            ),
            (
                "GHOSTTY_MOUSE_BUTTON_SIX",
                ffi::GHOSTTY_MOUSE_BUTTON_SIX as i64,
            ),
            (
                "GHOSTTY_MOUSE_BUTTON_SEVEN",
                ffi::GHOSTTY_MOUSE_BUTTON_SEVEN as i64,
            ),
            (
                "GHOSTTY_MOUSE_BUTTON_EIGHT",
                ffi::GHOSTTY_MOUSE_BUTTON_EIGHT as i64,
            ),
            (
                "GHOSTTY_MOUSE_BUTTON_NINE",
                ffi::GHOSTTY_MOUSE_BUTTON_NINE as i64,
            ),
            (
                "GHOSTTY_MOUSE_BUTTON_TEN",
                ffi::GHOSTTY_MOUSE_BUTTON_TEN as i64,
            ),
            (
                "GHOSTTY_MOUSE_BUTTON_ELEVEN",
                ffi::GHOSTTY_MOUSE_BUTTON_ELEVEN as i64,
            ),
            (
                "GHOSTTY_MOUSE_BUTTON_MAX_VALUE",
                ffi::GHOSTTY_MOUSE_BUTTON_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyMouseTrackingMode",
        size: size_of::<ffi::GhosttyMouseTrackingMode>(),
        align: align_of::<ffi::GhosttyMouseTrackingMode>(),
        values: &[
            (
                "GHOSTTY_MOUSE_TRACKING_NONE",
                ffi::GHOSTTY_MOUSE_TRACKING_NONE as i64,
            ),
            (
                "GHOSTTY_MOUSE_TRACKING_X10",
                ffi::GHOSTTY_MOUSE_TRACKING_X10 as i64,
            ),
            (
                "GHOSTTY_MOUSE_TRACKING_NORMAL",
                ffi::GHOSTTY_MOUSE_TRACKING_NORMAL as i64,
            ),
            (
                "GHOSTTY_MOUSE_TRACKING_BUTTON",
                ffi::GHOSTTY_MOUSE_TRACKING_BUTTON as i64,
            ),
            (
                "GHOSTTY_MOUSE_TRACKING_ANY",
                ffi::GHOSTTY_MOUSE_TRACKING_ANY as i64,
            ),
            (
                "GHOSTTY_MOUSE_TRACKING_MAX_VALUE",
                ffi::GHOSTTY_MOUSE_TRACKING_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyMouseFormat",
        size: size_of::<ffi::GhosttyMouseFormat>(),
        align: align_of::<ffi::GhosttyMouseFormat>(),
        values: &[
            (
                "GHOSTTY_MOUSE_FORMAT_X10",
                ffi::GHOSTTY_MOUSE_FORMAT_X10 as i64,
            ),
            (
                "GHOSTTY_MOUSE_FORMAT_UTF8",
                ffi::GHOSTTY_MOUSE_FORMAT_UTF8 as i64,
            ),
            (
                "GHOSTTY_MOUSE_FORMAT_SGR",
                ffi::GHOSTTY_MOUSE_FORMAT_SGR as i64,
            ),
            (
                "GHOSTTY_MOUSE_FORMAT_URXVT",
                ffi::GHOSTTY_MOUSE_FORMAT_URXVT as i64,
            ),
            (
                "GHOSTTY_MOUSE_FORMAT_SGR_PIXELS",
                ffi::GHOSTTY_MOUSE_FORMAT_SGR_PIXELS as i64,
            ),
            (
                "GHOSTTY_MOUSE_FORMAT_MAX_VALUE",
                ffi::GHOSTTY_MOUSE_FORMAT_MAX_VALUE as i64,
            ),
        ],
    },
    Enum {
        name: "GhosttyMouseEncoderOption",
        size: size_of::<ffi::GhosttyMouseEncoderOption>(),
        align: align_of::<ffi::GhosttyMouseEncoderOption>(),
        values: &[
            (
                "GHOSTTY_MOUSE_ENCODER_OPT_EVENT",
                ffi::GHOSTTY_MOUSE_ENCODER_OPT_EVENT as i64,
            ),
            (
                "GHOSTTY_MOUSE_ENCODER_OPT_FORMAT",
                ffi::GHOSTTY_MOUSE_ENCODER_OPT_FORMAT as i64,
            ),
            (
                "GHOSTTY_MOUSE_ENCODER_OPT_SIZE",
                ffi::GHOSTTY_MOUSE_ENCODER_OPT_SIZE as i64,
            ),
            (
                "GHOSTTY_MOUSE_ENCODER_OPT_ANY_BUTTON_PRESSED",
                ffi::GHOSTTY_MOUSE_ENCODER_OPT_ANY_BUTTON_PRESSED as i64,
            ),
            (
                "GHOSTTY_MOUSE_ENCODER_OPT_TRACK_LAST_CELL",
                ffi::GHOSTTY_MOUSE_ENCODER_OPT_TRACK_LAST_CELL as i64,
            ),
            (
                "GHOSTTY_MOUSE_ENCODER_OPT_MAX_VALUE",
                ffi::GHOSTTY_MOUSE_ENCODER_OPT_MAX_VALUE as i64,
            ),
        ],
    },
];

/// Unions: size and alignment only; every field sits at offset zero.
pub(crate) const UNIONS: &[Sized] = &[
    Sized {
        name: "GhosttyStyleColorValue",
        size: size_of::<ffi::GhosttyStyleColorValue>(),
        align: align_of::<ffi::GhosttyStyleColorValue>(),
    },
    Sized {
        name: "GhosttyPointValue",
        size: size_of::<ffi::GhosttyPointValue>(),
        align: align_of::<ffi::GhosttyPointValue>(),
    },
    Sized {
        name: "GhosttyTerminalScrollViewportValue",
        size: size_of::<ffi::GhosttyTerminalScrollViewportValue>(),
        align: align_of::<ffi::GhosttyTerminalScrollViewportValue>(),
    },
];

/// Scalar typedefs such as `GhosttyCell` and `GhosttyMode`.
pub(crate) const ALIASES: &[Sized] = &[
    Sized {
        name: "GhosttyColorPaletteIndex",
        size: size_of::<ffi::GhosttyColorPaletteIndex>(),
        align: align_of::<ffi::GhosttyColorPaletteIndex>(),
    },
    Sized {
        name: "GhosttyCell",
        size: size_of::<ffi::GhosttyCell>(),
        align: align_of::<ffi::GhosttyCell>(),
    },
    Sized {
        name: "GhosttyRow",
        size: size_of::<ffi::GhosttyRow>(),
        align: align_of::<ffi::GhosttyRow>(),
    },
    Sized {
        name: "GhosttyMode",
        size: size_of::<ffi::GhosttyMode>(),
        align: align_of::<ffi::GhosttyMode>(),
    },
];

/// Opaque handle typedefs.
pub(crate) const HANDLES: &[Sized] = &[
    Sized {
        name: "GhosttyTerminal",
        size: size_of::<ffi::GhosttyTerminal>(),
        align: align_of::<ffi::GhosttyTerminal>(),
    },
    Sized {
        name: "GhosttyRenderState",
        size: size_of::<ffi::GhosttyRenderState>(),
        align: align_of::<ffi::GhosttyRenderState>(),
    },
    Sized {
        name: "GhosttyRenderStateRowIterator",
        size: size_of::<ffi::GhosttyRenderStateRowIterator>(),
        align: align_of::<ffi::GhosttyRenderStateRowIterator>(),
    },
    Sized {
        name: "GhosttyRenderStateRowCells",
        size: size_of::<ffi::GhosttyRenderStateRowCells>(),
        align: align_of::<ffi::GhosttyRenderStateRowCells>(),
    },
    Sized {
        name: "GhosttyMouseEvent",
        size: size_of::<ffi::GhosttyMouseEvent>(),
        align: align_of::<ffi::GhosttyMouseEvent>(),
    },
    Sized {
        name: "GhosttyMouseEncoder",
        size: size_of::<ffi::GhosttyMouseEncoder>(),
        align: align_of::<ffi::GhosttyMouseEncoder>(),
    },
];
