//! Generated C declarations and the traits that tie each getter or option
//! key to the Rust type its header annotation names.
//!
//! `bindings.rs`, `keys.rs`, and `layout.rs` are generated by
//! `mise run ghostty:bindings`; `mise run ghostty:bindings:check` fails when
//! they are stale. Only `native.rs` and `callbacks.rs` call into this module.

#[expect(
    unsafe_code,
    reason = "bindgen emits `unsafe extern` blocks and zeroing `Default` impls"
)]
#[allow(
    dead_code,
    missing_debug_implementations,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    clippy::all,
    clippy::pedantic,
    clippy::undocumented_unsafe_blocks,
    reason = "generated declarations mirror the C headers"
)]
pub(crate) mod bindings;
pub(crate) mod keys;
#[cfg(test)]
#[allow(
    clippy::cast_lossless,
    reason = "enum constants widen to i64 in a const table"
)]
pub(crate) mod layout;

pub(crate) use bindings::*;

/// A key for `ghostty_terminal_get`; `Out` is the documented output type.
pub(crate) trait TerminalData {
    const KEY: GhosttyTerminalData;
    type Out;
}

/// A `ghostty_terminal_set` option whose value is passed by pointer.
pub(crate) trait TerminalOption {
    const KEY: GhosttyTerminalOption;
    type Value;
}

/// A `ghostty_terminal_set` option whose value is a callback pointer.
pub(crate) trait TerminalCallback {
    const KEY: GhosttyTerminalOption;
    type Callback;
}

/// A `ghostty_terminal_set` option whose value is an untyped pointer.
pub(crate) trait TerminalPointer {
    const KEY: GhosttyTerminalOption;
}

/// A callback typedef, passed to `ghostty_terminal_set` as the value
/// pointer itself.
pub(crate) trait CallbackPointer: Copy {
    fn as_pointer(self) -> *const core::ffi::c_void;
}

impl<A, B, R> CallbackPointer for Option<unsafe extern "C" fn(A, B) -> R> {
    fn as_pointer(self) -> *const core::ffi::c_void {
        self.map_or(core::ptr::null(), |callback| callback as *const _)
    }
}

impl<A, B, C, R> CallbackPointer
    for Option<unsafe extern "C" fn(A, B, C) -> R>
{
    fn as_pointer(self) -> *const core::ffi::c_void {
        self.map_or(core::ptr::null(), |callback| callback as *const _)
    }
}

impl<A, B, C, D, R> CallbackPointer
    for Option<unsafe extern "C" fn(A, B, C, D) -> R>
{
    fn as_pointer(self) -> *const core::ffi::c_void {
        self.map_or(core::ptr::null(), |callback| callback as *const _)
    }
}

/// A key for `ghostty_render_state_get`.
pub(crate) trait RenderStateData {
    const KEY: GhosttyRenderStateData;
    type Out;
}

/// A key for `ghostty_render_state_row_get`.
pub(crate) trait RenderRowData {
    const KEY: GhosttyRenderStateRowData;
    type Out;
}

/// A key for `ghostty_render_state_row_cells_get`.
pub(crate) trait RenderCellData {
    const KEY: GhosttyRenderStateRowCellsData;
    type Out;
}

/// A key for `ghostty_cell_get`.
pub(crate) trait CellData {
    const KEY: GhosttyCellData;
    type Out;
}

/// A key for `ghostty_row_get`.
pub(crate) trait RowData {
    const KEY: GhosttyRowData;
    type Out;
}

/// A `ghostty_mouse_encoder_setopt` option, passed by pointer.
pub(crate) trait MouseEncoderOption {
    const KEY: GhosttyMouseEncoderOption;
    type Value;
}

/// A key for `ghostty_build_info`.
pub(crate) trait BuildInfo {
    const KEY: GhosttyBuildInfo;
    type Out;
}

/// A struct whose first field is `size_t size`, which the library reads to
/// learn which version of the struct the caller compiled against.
pub(crate) trait SizedStruct: Default {
    fn size_mut(&mut self) -> &mut usize;
}

/// Zero-initializes a sized struct and sets its `size` field, like the
/// header's `GHOSTTY_INIT_SIZED`.
pub(crate) fn sized<T: SizedStruct>() -> T {
    let mut value = T::default();
    *value.size_mut() = size_of::<T>();
    value
}

/// Packs a mode like the header's inline `ghostty_mode_new`: bits 0-14 hold
/// the value and bit 15 marks an ANSI mode.
pub(crate) const fn mode(value: u16, ansi: bool) -> GhosttyMode {
    let flag: u16 = if ansi { 1 << 15 } else { 0 };
    (value & 0x7fff) | flag
}
